[package]
name = "review_db"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
chrono = "0.4.19"
colored = "2.0.0"
git2 = "0.13.15"
itertools = "0.10.0"
