[package]
name = "incoming"
description = "A local database of gitlab MR revisions"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
git2 = "0.13.17"
gitlab = "0.1210.0"
serde_json = "1.0.62"
sled = "0.34.6"
structopt = "0.3.21"
tracing = "0.1.23"
tracing-subscriber = "0.2.15"
yansi = "0.5.0"
