[package]
name = "mr_db"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
git2 = "0.13.17"
gitlab = "0.1210.0"
sled = "0.34.6"
tracing = "0.1.23"
